package opusliews;

import necesse.engine.localization.message.LocalMessage;
import necesse.engine.registries.GlobalIngredientRegistry;
import necesse.engine.registries.ItemRegistry;
import necesse.inventory.item.Item;
import necesse.inventory.item.matItem.MatItem;
import opusliews.armor.BuilderBootsArmorItem;
import opusliews.armor.BuilderHatArmorItem;
import opusliews.armor.BuilderShirtArmorItem;
import opusliews.crafting.CraftingComponentCategories;
import opusliews.crafting.CraftingMaterialItem;
import opusliews.item.*;

public class DSItemRegistry {
	public static final String featherStringID = "feather";
	public static final String groundFiremoneStringID = "groundfiremone";
	public static final String honeycombFragmentStringID = "honeycombfragment";
	public static final String waxStringID = "wax";
	public static final String oakplankStringID = "oakplank";
	public static final String nailStringID = "nail";
	public static final String hingeStringID = "hinge";
	public static final String spruceplankStringID = "spruceplank";
	public static final String pineplankStringID = "pineplank";
	public static final String palmplankStringID = "palmplank";
	public static final String birchplankStringID = "birchplank";
	public static final String willowplankStringID = "willowplank";
	public static final String mapleplankStringID = "mapleplank";
	public static final String deadwoodplankStringID = "deadwoodplank";
	public static final String bambooplankStringID = "bambooplank";
	public static final String dryadplankStringID = "dryadplank";
	public static final String woodenshaftStringID = "woodenshaft";
	public static final String coppershaftStringID = "coppershaft";
	public static final String ironshaftStringID = "ironshaft";
	public static final String goldshaftStringID = "goldshaft";
	public static final String tungstenshaftStringID = "tungstenshaft";
	public static final String demonicshaftStringID = "demonicshaft";
	public static final String ivyshaftStringID = "ivyshaft";
	public static final String quartzshaftStringID = "quartzshaft";
	public static final String slimeshaftStringID = "slimeshaft";
	public static final String glacialshaftStringID = "glacialshaft";
	public static final String dryadshaftStringID = "dryadshaft";
	public static final String myceliumshaftStringID = "myceliumshaft";
	public static final String spideriteshaftStringID = "spideriteshaft";
	public static final String arcanicshaftStringID = "arcanicshaft";
	public static final String voidshaftStringID = "voidshaft";
	public static final String copperplateStringID = "copperplate";
	public static final String ironplateStringID = "ironplate";
	public static final String goldplateStringID = "goldplate";
	public static final String tungstenplateStringID = "tungstenplate";
	public static final String demonicplateStringID = "demonicplate";
	public static final String ivyplateStringID = "ivyplate";
	public static final String quartzplateStringID = "quartzplate";
	public static final String slimeplateStringID = "slimeplate";
	public static final String glacialplateStringID = "glacialplate";
	public static final String dryadplateStringID = "dryadplate";
	public static final String myceliumplateStringID = "myceliumplate";
	public static final String runicplateStringID = "runicplate";
	public static final String spideriteplateStringID = "spideriteplate";
	public static final String nightsteelplateStringID = "nightsteelplate";
	public static final String ancientfossilplateStringID = "ancientfossilplate";
	public static final String arcanicplateStringID = "arcanicplate";
	public static final String crystalplateStringID = "crystalplate";
	public static final String emeraldplateStringID = "emeraldplate";
	public static final String rubyplateStringID = "rubyplate";
	public static final String amethystplateStringID = "amethystplate";
	public static final String bloodplateplateStringID = "bloodplateplate";
	public static final String spiderplateStringID = "spiderplate";
	public static final String voidplateStringID = "voidplate";
	public static final String woodenbladeStringID = "woodenblade";
	public static final String copperbladeStringID = "copperblade";
	public static final String ironbladeStringID = "ironblade";
	public static final String goldbladeStringID = "goldblade";
	public static final String tungstenbladeStringID = "tungstenblade";
	public static final String demonicbladeStringID = "demonicblade";
	public static final String ivybladeStringID = "ivyblade";
	public static final String quartzbladeStringID = "quartzblade";
	public static final String glacialbladeStringID = "glacialblade";
	public static final String slimebladeStringID = "slimeblade";
	public static final String amethystbladeStringID = "amethystblade";
	public static final String copperPickaxeHeadStringID = "copperpickaxehead";
	public static final String copperAxeHeadStringID = "copperaxehead";
	public static final String copperShovelHeadStringID = "coppershovelhead";
	public static final String ironPickaxeHeadStringID = "ironpickaxehead";
	public static final String ironAxeHeadStringID = "ironaxehead";
	public static final String ironShovelHeadStringID = "ironshovelhead";
	public static final String goldPickaxeHeadStringID = "goldpickaxehead";
	public static final String goldAxeHeadStringID = "goldaxehead";
	public static final String goldShovelHeadStringID = "goldshovelhead";
	public static final String frostPickaxeHeadStringID = "frostpickaxehead";
	public static final String frostAxeHeadStringID = "frostaxehead";
	public static final String frostShovelHeadStringID = "frostshovelhead";
	public static final String demonicPickaxeHeadStringID = "demonicpickaxehead";
	public static final String demonicAxeHeadStringID = "demonicaxehead";
	public static final String demonicShovelHeadStringID = "demonicshovelhead";
	public static final String runicPickaxeHeadStringID = "runicpickaxehead";
	public static final String runicAxeHeadStringID = "runicaxehead";
	public static final String runicShovelHeadStringID = "runicshovelhead";
	public static final String ivyPickaxeHeadStringID = "ivypickaxehead";
	public static final String ivyAxeHeadStringID = "ivyaxehead";
	public static final String ivyShovelHeadStringID = "ivyshovelhead";
	public static final String quartzPickaxeHeadStringID = "quartzpickaxehead";
	public static final String quartzAxeHeadStringID = "quartzaxehead";
	public static final String quartzShovelHeadStringID = "quartzshovelhead";
	public static final String tungstenPickaxeHeadStringID = "tungstenpickaxehead";
	public static final String tungstenAxeHeadStringID = "tungstenaxehead";
	public static final String tungstenShovelHeadStringID = "tungstenshovelhead";
	public static final String glacialPickaxeHeadStringID = "glacialpickaxehead";
	public static final String glacialAxeHeadStringID = "glacialaxehead";
	public static final String glacialShovelHeadStringID = "glacialshovelhead";
	public static final String dryadPickaxeHeadStringID = "dryadpickaxehead";
	public static final String dryadAxeHeadStringID = "dryadaxehead";
	public static final String dryadShovelHeadStringID = "dryadshovelhead";
	public static final String myceliumPickaxeHeadStringID = "myceliumpickaxehead";
	public static final String myceliumAxeHeadStringID = "myceliumaxehead";
	public static final String myceliumShovelHeadStringID = "myceliumshovelhead";
	public static final String ancientfossilPickaxeHeadStringID = "ancientfossilpickaxehead";
	public static final String ancientfossilAxeHeadStringID = "ancientfossilaxehead";
	public static final String ancientfossilShovelHeadStringID = "ancientfossilshovelhead";
	public static final String ironSickleBladeStringID = "ironsickleblade";
	public static final String ironShearsBladeStringID = "ironshearsblade";
	public static final String stringStringID = "string";
	public static final String clothpanelStringID = "clothpanel";
	public static final String bonepanelStringID = "bonepanel";
	public static final String slimearmorpanelStringID = "slimearmorpanel";
	public static final String dryadarmorpanelStringID = "dryadarmorpanel";
	public static final String runicarmorpanelStringID = "runicarmorpanel";
	public static final String hookStringID = "metalhook";
	public static final String metalcasingStringID = "metalcasing";
	public static final String clockworkmechanismStringID = "clockworkmechanism";
	public static final String magicfocusStringID = "magicfocus";
	public static final String unfiredBrickStringID = "unfiredbrick";
	public static final String brickStringID = "brick";
	public static final String unfiredIngotMoldStringID = "unfiredingotmold";
	public static final String ingotMoldStringID = "ingotmold";
	public static final String unfiredPickaxeHeadMoldStringID = "unfiredpickaxeheadmold";
	public static final String pickaxeHeadMoldStringID = "pickaxeheadmold";
	public static final String unfiredAxeHeadMoldStringID = "unfiredaxeheadmold";
	public static final String axeHeadMoldStringID = "axeheadmold";
	public static final String unfiredShovelHeadMoldStringID = "unfiredshovelheadmold";
	public static final String shovelHeadMoldStringID = "shovelheadmold";
	public static final String unfiredSickleBladeMoldStringID = "unfiredsickleblademold";
	public static final String sickleBladeMoldStringID = "sickleblademold";
	public static final String unfiredShearsBladeMoldStringID = "unfiredshearsblademold";
	public static final String shearsBladeMoldStringID = "shearsblademold";
	public static final String unfiredSwordBladeMoldStringID = "unfiredswordblademold";
	public static final String swordBladeMoldStringID = "swordblademold";
	public static final String unfiredThickPlateMoldStringID = "unfiredthickplatemold";
	public static final String thickPlateMoldStringID = "thickplatemold";
	public static final String thickIronPlateStringID = "thickironplate";
	public static final String clayPackageStringID = "claypackage";

	public static void registerItems() {
		registerGlobalGroups();
		CraftingComponentCategories.register();

		ItemRegistry.registerItem("builderhat", new BuilderHatArmorItem(), 50.0F, true);
		ItemRegistry.registerItem("buildershirt", new BuilderShirtArmorItem(), 50.0F, true);
		ItemRegistry.registerItem("builderboots", new BuilderBootsArmorItem(), 50.0F, true);
		ItemRegistry.registerItem("blueprintItem", new BlueprintItem(), 25.0F, true);
		ItemRegistry.registerItem("projecteraser", new ProjectEraserItem(), 30.0F, true);
		ItemRegistry.registerItem("inspectionglass", new InspectionGlassItem(), 20.0F, true);
		ItemRegistry.registerItem("malignancegoggles", new MalignanceGogglesItem(), 100.0F, true);
		ItemRegistry.registerItem(TreasureShovelItem.stringID, new TreasureShovelItem(), 200.0F, true);
		ItemRegistry.registerItem(clayPackageStringID, new ClayPackageItem(), 0.0F, false, false, false);

		registerMaterial(featherStringID, new MatItem(500, Item.Rarity.NORMAL), 3.0F, "ingredient", "organic", "feather");
		registerMaterial(groundFiremoneStringID, new MatItem(500, Item.Rarity.NORMAL), 8.0F, "ingredient", "organic", "firemone");
		registerMaterial(honeycombFragmentStringID, new MatItem(500, Item.Rarity.NORMAL), 5.0F, "ingredient", "organic", "honeycomb");
		registerMaterial(waxStringID, new MatItem(500, Item.Rarity.NORMAL), 6.0F, "ingredient", "organic", "honeycomb");

		registerMaterial(oakplankStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplank"), 5.0F, "plank", "wood", "oak");
		registerMaterial(nailStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL), 5.0F, "nail", "metal", "metal");
		registerMaterial(hingeStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL), 5.0F, "hinge", "metal", "metal");
		registerMaterial(spruceplankStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplank"), 5.0F, "plank", "wood", "spruce");
		registerMaterial(pineplankStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplank"), 5.0F, "plank", "wood", "pine");
		registerMaterial(palmplankStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplank"), 5.0F, "plank", "wood", "palm");
		registerMaterial(birchplankStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplank"), 5.0F, "plank", "wood", "birch");
		registerMaterial(willowplankStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplank"), 5.0F, "plank", "wood", "willow");
		registerMaterial(mapleplankStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplank"), 5.0F, "plank", "wood", "maple");
		registerMaterial(deadwoodplankStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplank"), 5.0F, "plank", "wood", "deadwood");
		registerMaterial(bambooplankStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplank"), 5.0F, "plank", "wood", "bamboo");
		registerMaterial(dryadplankStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplank"), 5.0F, "plank", "wood", "dryad");
		registerMaterial(woodenshaftStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshaft"), 5.0F, "shaft", "wood", "wooden");
		registerMaterial(coppershaftStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshaft", "dsanymetalshaft"), 5.0F, "shaft", "metal", "copper");
		registerMaterial(ironshaftStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshaft", "dsanymetalshaft"), 5.0F, "shaft", "metal", "iron");
		registerMaterial(goldshaftStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshaft", "dsanymetalshaft"), 5.0F, "shaft", "metal", "gold");
		registerMaterial(tungstenshaftStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshaft", "dsanymetalshaft"), 5.0F, "shaft", "metal", "tungsten");
		registerMaterial(demonicshaftStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshaft", "dsanymetalshaft"), 5.0F, "shaft", "metal", "demonic");
		registerMaterial(ivyshaftStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshaft"), 5.0F, "shaft", "organic", "ivy");
		registerMaterial(quartzshaftStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshaft"), 5.0F, "shaft", "gem", "quartz");
		registerMaterial(slimeshaftStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshaft"), 5.0F, "shaft", "organic", "slime");
		registerMaterial(glacialshaftStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshaft", "dsanymetalshaft"), 5.0F, "shaft", "metal", "glacial");
		registerMaterial(dryadshaftStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshaft"), 5.0F, "shaft", "wood", "dryad");
		registerMaterial(myceliumshaftStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshaft"), 5.0F, "shaft", "organic", "mycelium");
		registerMaterial(spideriteshaftStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshaft", "dsanymetalshaft"), 5.0F, "shaft", "metal", "spiderite");
		registerMaterial(arcanicshaftStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshaft"), 5.0F, "shaft", "magic", "arcanic");
		registerMaterial(voidshaftStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshaft"), 5.0F, "shaft", "magic", "void");
		registerMaterial(copperplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate", "dsanymetalplate"), 5.0F, "plate", "metal", "copper");
		registerMaterial(ironplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate", "dsanymetalplate"), 5.0F, "plate", "metal", "iron");
		registerMaterial(goldplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate", "dsanymetalplate"), 5.0F, "plate", "metal", "gold");
		registerMaterial(tungstenplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate", "dsanymetalplate"), 5.0F, "plate", "metal", "tungsten");
		registerMaterial(demonicplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate", "dsanymetalplate"), 5.0F, "plate", "metal", "demonic");
		registerMaterial(ivyplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate"), 5.0F, "plate", "organic", "ivy");
		registerMaterial(quartzplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate"), 5.0F, "plate", "gem", "quartz");
		registerMaterial(slimeplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate"), 5.0F, "plate", "organic", "slime");
		registerMaterial(glacialplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate", "dsanymetalplate"), 5.0F, "plate", "metal", "glacial");
		registerMaterial(dryadplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate"), 5.0F, "plate", "wood", "dryad");
		registerMaterial(myceliumplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate"), 5.0F, "plate", "organic", "mycelium");
		registerMaterial(runicplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate"), 5.0F, "plate", "magic", "runic");
		registerMaterial(spideriteplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate", "dsanymetalplate"), 5.0F, "plate", "metal", "spiderite");
		registerMaterial(nightsteelplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate", "dsanymetalplate"), 5.0F, "plate", "metal", "nightsteel");
		registerMaterial(ancientfossilplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate", "dsanymetalplate"), 5.0F, "plate", "metal", "ancientfossil");
		registerMaterial(arcanicplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate"), 5.0F, "plate", "magic", "arcanic");
		registerMaterial(crystalplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate"), 5.0F, "plate", "gem", "crystal");
		registerMaterial(emeraldplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate"), 5.0F, "plate", "gem", "emerald");
		registerMaterial(rubyplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate"), 5.0F, "plate", "gem", "ruby");
		registerMaterial(amethystplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate"), 5.0F, "plate", "gem", "amethyst");
		registerMaterial(bloodplateplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate", "dsanymetalplate"), 5.0F, "plate", "metal", "bloodplate");
		registerMaterial(spiderplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate"), 5.0F, "plate", "organic", "spider");
		registerMaterial(voidplateStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyplate"), 5.0F, "plate", "magic", "void");
		registerMaterial(woodenbladeStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyblade"), 5.0F, "blade", "wood", "wooden");
		registerMaterial(copperbladeStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyblade", "dsanymetalblade"), 5.0F, "blade", "metal", "copper");
		registerMaterial(ironbladeStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyblade", "dsanymetalblade"), 5.0F, "blade", "metal", "iron");
		registerMaterial(goldbladeStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyblade", "dsanymetalblade"), 5.0F, "blade", "metal", "gold");
		registerMaterial(tungstenbladeStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyblade", "dsanymetalblade"), 5.0F, "blade", "metal", "tungsten");
		registerMaterial(demonicbladeStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyblade", "dsanymetalblade"), 5.0F, "blade", "metal", "demonic");
		registerMaterial(ivybladeStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyblade"), 5.0F, "blade", "organic", "ivy");
		registerMaterial(quartzbladeStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyblade"), 5.0F, "blade", "gem", "quartz");
		registerMaterial(glacialbladeStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyblade", "dsanymetalblade"), 5.0F, "blade", "metal", "glacial");
		registerMaterial(slimebladeStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyblade"), 5.0F, "blade", "organic", "slime");
		registerMaterial(amethystbladeStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyblade"), 5.0F, "blade", "gem", "amethyst");

		// Molded tool components
		registerMaterial(copperPickaxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanypickaxehead"), 5.0F, "pickaxehead", "metal", "copper");
		registerMaterial(copperAxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyaxehead"), 5.0F, "axehead", "metal", "copper");
		registerMaterial(copperShovelHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshovelhead"), 5.0F, "shovelhead", "metal", "copper");
		registerMaterial(ironPickaxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanypickaxehead"), 5.0F, "pickaxehead", "metal", "iron");
		registerMaterial(ironAxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyaxehead"), 5.0F, "axehead", "metal", "iron");
		registerMaterial(ironShovelHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshovelhead"), 5.0F, "shovelhead", "metal", "iron");
		registerMaterial(goldPickaxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanypickaxehead"), 5.0F, "pickaxehead", "metal", "gold");
		registerMaterial(goldAxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyaxehead"), 5.0F, "axehead", "metal", "gold");
		registerMaterial(goldShovelHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshovelhead"), 5.0F, "shovelhead", "metal", "gold");
		registerMaterial(frostPickaxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanypickaxehead"), 5.0F, "pickaxehead", "magic", "frost");
		registerMaterial(frostAxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyaxehead"), 5.0F, "axehead", "magic", "frost");
		registerMaterial(frostShovelHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshovelhead"), 5.0F, "shovelhead", "magic", "frost");
		registerMaterial(demonicPickaxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanypickaxehead"), 5.0F, "pickaxehead", "metal", "demonic");
		registerMaterial(demonicAxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyaxehead"), 5.0F, "axehead", "metal", "demonic");
		registerMaterial(demonicShovelHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshovelhead"), 5.0F, "shovelhead", "metal", "demonic");
		registerMaterial(runicPickaxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanypickaxehead"), 5.0F, "pickaxehead", "magic", "runic");
		registerMaterial(runicAxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyaxehead"), 5.0F, "axehead", "magic", "runic");
		registerMaterial(runicShovelHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshovelhead"), 5.0F, "shovelhead", "magic", "runic");
		registerMaterial(ivyPickaxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanypickaxehead"), 5.0F, "pickaxehead", "organic", "ivy");
		registerMaterial(ivyAxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyaxehead"), 5.0F, "axehead", "organic", "ivy");
		registerMaterial(ivyShovelHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshovelhead"), 5.0F, "shovelhead", "organic", "ivy");
		registerMaterial(quartzPickaxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanypickaxehead"), 5.0F, "pickaxehead", "gem", "quartz");
		registerMaterial(quartzAxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyaxehead"), 5.0F, "axehead", "gem", "quartz");
		registerMaterial(quartzShovelHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshovelhead"), 5.0F, "shovelhead", "gem", "quartz");
		registerMaterial(tungstenPickaxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanypickaxehead"), 5.0F, "pickaxehead", "metal", "tungsten");
		registerMaterial(tungstenAxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyaxehead"), 5.0F, "axehead", "metal", "tungsten");
		registerMaterial(tungstenShovelHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshovelhead"), 5.0F, "shovelhead", "metal", "tungsten");
		registerMaterial(glacialPickaxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanypickaxehead"), 5.0F, "pickaxehead", "metal", "glacial");
		registerMaterial(glacialAxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyaxehead"), 5.0F, "axehead", "metal", "glacial");
		registerMaterial(glacialShovelHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshovelhead"), 5.0F, "shovelhead", "metal", "glacial");
		registerMaterial(dryadPickaxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanypickaxehead"), 5.0F, "pickaxehead", "wood", "dryad");
		registerMaterial(dryadAxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyaxehead"), 5.0F, "axehead", "wood", "dryad");
		registerMaterial(dryadShovelHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshovelhead"), 5.0F, "shovelhead", "wood", "dryad");
		registerMaterial(myceliumPickaxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanypickaxehead"), 5.0F, "pickaxehead", "organic", "mycelium");
		registerMaterial(myceliumAxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyaxehead"), 5.0F, "axehead", "organic", "mycelium");
		registerMaterial(myceliumShovelHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshovelhead"), 5.0F, "shovelhead", "organic", "mycelium");
		registerMaterial(ancientfossilPickaxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanypickaxehead"), 5.0F, "pickaxehead", "metal", "ancientfossil");
		registerMaterial(ancientfossilAxeHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyaxehead"), 5.0F, "axehead", "metal", "ancientfossil");
		registerMaterial(ancientfossilShovelHeadStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyshovelhead"), 5.0F, "shovelhead", "metal", "ancientfossil");
		registerMaterial(ironSickleBladeStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL), 5.0F, "sickleblade", "metal", "iron");
		registerMaterial(ironShearsBladeStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL), 5.0F, "shearsblade", "metal", "iron");
		registerMaterial(stringStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL), 5.0F, "string", "textile", "grass");
		registerMaterial(clothpanelStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyarmorpanel"), 5.0F, "armorpanel", "textile", "cloth");
		registerMaterial(bonepanelStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyarmorpanel"), 5.0F, "armorpanel", "bone", "bone");
		registerMaterial(slimearmorpanelStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyarmorpanel"), 5.0F, "armorpanel", "organic", "slime");
		registerMaterial(dryadarmorpanelStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyarmorpanel"), 5.0F, "armorpanel", "wood", "dryad");
		registerMaterial(runicarmorpanelStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL, "dsanyarmorpanel"), 5.0F, "armorpanel", "magic", "runic");
		registerMaterial(hookStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL), 5.0F, "hook", "metal", "metal");
		registerMaterial(metalcasingStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL), 5.0F, "casing", "metal", "metal");
		registerMaterial(clockworkmechanismStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL), 5.0F, "mechanism", "metal", "metal");
		registerMaterial(magicfocusStringID, new CraftingMaterialItem(500, Item.Rarity.NORMAL), 5.0F, "focus", "magic", "magic");
		registerMaterial(unfiredBrickStringID, new FireableMatItem(500, Item.Rarity.NORMAL, brickStringID), 1.0F, null, null, null);
		registerMaterial(brickStringID, new FiredClayMatItem(500, Item.Rarity.NORMAL), 2.0F, null, null, null);
		registerMaterial(unfiredIngotMoldStringID, new FireableMatItem(500, Item.Rarity.NORMAL, ingotMoldStringID), 1.0F, null, null, null);
		registerMaterial(ingotMoldStringID, new FiredClayMatItem(500, Item.Rarity.NORMAL), 2.0F, null, null, null);
		registerMaterial(unfiredPickaxeHeadMoldStringID, new FireableMatItem(500, Item.Rarity.NORMAL, pickaxeHeadMoldStringID), 1.0F, null, null, null);
		registerMaterial(pickaxeHeadMoldStringID, new FiredClayMatItem(500, Item.Rarity.NORMAL), 2.0F, null, null, null);
		registerMaterial(unfiredAxeHeadMoldStringID, new FireableMatItem(500, Item.Rarity.NORMAL, axeHeadMoldStringID), 1.0F, null, null, null);
		registerMaterial(axeHeadMoldStringID, new FiredClayMatItem(500, Item.Rarity.NORMAL), 2.0F, null, null, null);
		registerMaterial(unfiredShovelHeadMoldStringID, new FireableMatItem(500, Item.Rarity.NORMAL, shovelHeadMoldStringID), 1.0F, null, null, null);
		registerMaterial(shovelHeadMoldStringID, new FiredClayMatItem(500, Item.Rarity.NORMAL), 2.0F, null, null, null);
		registerMaterial(unfiredSickleBladeMoldStringID, new FireableMatItem(500, Item.Rarity.NORMAL, sickleBladeMoldStringID), 1.0F, null, null, null);
		registerMaterial(sickleBladeMoldStringID, new FiredClayMatItem(500, Item.Rarity.NORMAL), 2.0F, null, null, null);
		registerMaterial(unfiredShearsBladeMoldStringID, new FireableMatItem(500, Item.Rarity.NORMAL, shearsBladeMoldStringID), 1.0F, null, null, null);
		registerMaterial(shearsBladeMoldStringID, new FiredClayMatItem(500, Item.Rarity.NORMAL), 2.0F, null, null, null);
		registerMaterial(unfiredSwordBladeMoldStringID, new FireableMatItem(500, Item.Rarity.NORMAL, swordBladeMoldStringID), 1.0F, null, null, null);
		registerMaterial(swordBladeMoldStringID, new FiredClayMatItem(500, Item.Rarity.NORMAL), 2.0F, null, null, null);
		registerMaterial(unfiredThickPlateMoldStringID, new FireableMatItem(500, Item.Rarity.NORMAL, thickPlateMoldStringID), 1.0F, null, null, null);
		registerMaterial(thickPlateMoldStringID, new FiredClayMatItem(500, Item.Rarity.NORMAL), 2.0F, null, null, null);
		registerMaterial(thickIronPlateStringID, new MatItem(500, Item.Rarity.NORMAL), 20.0F, null, null, null);
	}

	private static void registerGlobalGroups() {
		registerGlobal("dsanyplank");
		registerGlobal("dsanyshaft");
		registerGlobal("dsanymetalshaft");
		registerGlobal("dsanyplate");
		registerGlobal("dsanymetalplate");
		registerGlobal("dsanyblade");
		registerGlobal("dsanymetalblade");
		registerGlobal("dsanypickaxehead");
		registerGlobal("dsanyaxehead");
		registerGlobal("dsanyshovelhead");
		registerGlobal("dsanyarmorpanel");
	}

	private static void registerGlobal(String id) {
		GlobalIngredientRegistry.registerGlobalIngredient(id, new LocalMessage("globalingredient", id), null);
	}

	private static void registerMaterial(String id, MatItem item, float brokerValue, String type, String materialClass, String material) {
		CraftingComponentCategories.categorize(item, emptyToNull(type), emptyToNull(materialClass), emptyToNull(material));
		ItemRegistry.registerItem(id, item, brokerValue, true);
	}

	private static String emptyToNull(String value) {
		return value == null || value.isEmpty() ? null : value;
	}
}
